export const employees = [
    {
        name:"Cole Ashbury",
        email:"cashbury@comp.com",
        id:1,
        role:"Software Engineer",
        department:"Engineering",
        phone:"112233324",
        availability:true,
        picture:"avatar-girl.jpeg",
        mobile:"(472)276-0193",
        office:"Atlanta",
        city:"Denver",
        birthday:"March 3",
        gender:"Female",
    },
    {
        name:"David Warner",
        email:"dwarner@comp.com",
        id:2,
        role:"Sales Consultant",
        department:"Sales",
        phone:"112233324",
        availability:true,
        picture:"avatar-boy.png",
        mobile:"(403)293-7845",
        office:"Texas",
        city:"Washington",
        birthday:"July 7",
        gender:"Male",
    },
    {
        name:"Mathey Hayden",
        email:"mhayden@comp.com",
        id:3,
        role:"Accountany",
        department:"Finance",
        phone:"112233324",
        availability:false,
        picture:"avatar-boy.png",
        mobile:"(307)563-5621",
        office:"Chicago",
        city:"Texas",
        birthday:"June 27",
        gender:"Male",
    },
    {
        name:"Suzan Mathew",
        email:"smathew@comp.com",
        id:4,
        role:"Product Designer",
        department:"Design",
        phone:"112233324",
        availability:true,
        picture:"avatar-girl.jpeg",
        mobile:"(222)541-890",
        office:"Texas",
        city:"Los Angelas",
        birthday:"August 7",
        gender:"Female",
    },
    {
        name:"Lisa Bradford",
        email:"lbradford@comp.com",
        id:5,
        role:"Software Engineer",
        department:"Engineering",
        phone:"112233324",
        availability:false,
        picture:"avatar-girl.jpeg",
        mobile:"(455)654-0198",
        office:"Atlanta",
        city:"seatle",
        birthday:"May 15",
        gender:"Female",
    },
    {
        name:"Paul Breny",
        email:"pbreny@comp.com",
        id:6,
        role:"Marketing Coordinator",
        department:"Marketing",
        phone:"112233324",
        availability:true,
        picture:"avatar-boy.png",
        mobile:"(422)903-4888",
        office:"Chicago",
        city:"Denver",
        birthday:"December 17",
        gender:"Male",
    },
    {
        name:"John",
        email:"john13@comp.com",
        id:7,
        role:"Marketing Coordinator",
        department:"Marketing",
        phone:"112233324",
        availability:true,
        picture:"avatar-boy.png",
        mobile:"(422)903-4888",
        office:"Denver",
        city:"Denver",
        birthday:"December 17",
        gender:"Male",
    },
    {
        name:"Miliana",
        email:"miliana.s@comp.com",
        id:8,
        role:"Software Engineer",
        department:"Engineering",
        phone:"112233324",
        availability:false,
        picture:"avatar-girl.jpeg",
        mobile:"(422)903-4888",
        office:"Texas",
        city:"Texas",
        birthday:"December 30",
        gender:"Female",
    },
    {
        name:"Isabella",
        email:"isabella.s@comp.com",
        id:9,
        role:"Sales Consultant",
        department:"Sales",
        phone:"112984324",
        availability:true,
        picture:"avatar-girl.jpeg",
        mobile:"(422)903-5308",
        office:"Chicago",
        city:"Chicago",
        birthday:"January 31",
        gender:"Female",
    },
    
]